name: Minikube
on:   
  - push 
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build discover and deploy 
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
    - name: Start minikube
      uses: medyagh/setup-minikube@latest
      # now you can run kubectl to see the pods in the cluster
    - name: Try the cluster!
      run: kubectl get pods -A
